language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=9.11
  matrix:
    - TAG=9.11 NODE_VER=9.11.1 EXTRA_TAG=9
    - TAG=8.11 NODE_VER=8.11.1 EXTRA_TAG=8

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release"
