language: bash

services:
- docker

env:
  matrix:
  - NODE_VER=12.17.0 TAGS=12.17,12,latest
  - NODE_VER=10.20.1 TAGS=10.20,10
  - NODE_VER=8.17.0 TAGS=8.17,8
  - NODE_VER=12.17.0 NODE_DEV=1 TAGS=12.13-dev,12-dev,dev
  - NODE_VER=10.20.1 NODE_DEV=1 TAGS=10.17-dev,10-dev
  - NODE_VER=8.17.0 NODE_DEV=1 TAGS=8.16-dev,8-dev

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
