language: bash

services:
  - docker

env:
  matrix:
    - NODE_VER=10.15.2 TAGS=10.15,10,latest
    - NODE_VER=8.15.1 TAGS=8.15,8
    - NODE_VER=6.17.0 TAGS=6.17,6

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
