language: bash

services:
  - docker

env:
  matrix:
  - NODE_VER=12.9.0 TAGS=12.9,12,latest
  - NODE_VER=10.16.3 TAGS=10.16,10
  - NODE_VER=8.16.1 TAGS=8.16,8

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
