language: bash

services:
  - docker

env:
  matrix:
    - NODE_VER=10.11.0 TAGS=10.11,10,latest
    - NODE_VER=8.12.0 TAGS=8.12,8
    - NODE_VER=6.14.4 TAGS=6.14,6

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
