language: bash

services:
  - docker

env:
  matrix:
    - NODE_VER=9.11.2 TAGS=9.11,9,latest
    - NODE_VER=8.11.3 TAG=8.11,8
    - NODE_VER=6.14.3 TAG=6.14,6

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
