name: Build
description: Build node image
inputs:
  version:
    description: version
    required: true
  tags:
    description: image tags
    required: true
  dev:
    description: dev version of the image
    required: false
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      NODE_VER: ${{ inputs.version }}
      NODE_DEV: ${{ inputs.dev }}
      TAGS: ${{ inputs.tags }}
    run: |
      set -e
      make
      make test
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
