name: Build
description: Build node image
inputs:
  version:
    description: version
    required: true
  tags:
    description: image tags
    required: true
  dev:
    description: dev version of the image
    required: false
  platform:
    description: docker platform
    required: false
    default: linux/amd64
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      NODE_VER: ${{ inputs.version }}
      NODE_DEV: ${{ inputs.dev }}
      TAGS: ${{ inputs.tags }}
      PLATFORM: ${{ inputs.platform }}
    run: |
      set -e
      make buildx-build-amd64
      make test
      make buildx-build
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
