name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  NODE18: '18.6.0'
  NODE16: '16.16.0'
  NODE14: '14.20.0'
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  node18:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE18 }}
        tags: 18.6,18,latest
  node16:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE16 }}
        tags: 16.16,16
  node14:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE14 }}
        tags: 14.20,14
  node18-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE18 }}
        tags: 18.6-dev,18-dev,dev
        dev: 1
  node16-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE16 }}
        tags: 16.16-dev,16-dev
        dev: 1
  node14-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE14 }}
        tags: 14.20-dev,14-dev
        dev: 1
