name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  NODE20: '20.10.0'
  NODE18: '18.18.2'
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  node20:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE20 }}
        tags: 20.10,20,latest
        platform: linux/amd64,linux/arm64
  node18:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE18 }}
        tags: 18.18,18
        platform: linux/amd64,linux/arm64
  node20-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE20 }}
        tags: 20.10-dev,20-dev,dev
        dev: 1
        platform: linux/amd64,linux/arm64
  node18-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE18 }}
        tags: 18.18-dev,18-dev
        dev: 1
        platform: linux/amd64,linux/arm64
