name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  NODE18: '18.12.1'
  NODE16: '16.18.0'
  NODE14: '14.21.0'
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  node18:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE18 }}
        tags: 18.12,18,latest
        platform: linux/amd64,linux/arm64
  node16:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE16 }}
        tags: 16.18,16
        platform: linux/amd64,linux/arm64
  node14:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE14 }}
        tags: 14.21,14
        platform: linux/amd64,linux/arm64
  node18-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE18 }}
        tags: 18.12-dev,18-dev,dev
        dev: 1
        platform: linux/amd64,linux/arm64
  node16-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE16 }}
        tags: 16.18-dev,16-dev
        dev: 1
        platform: linux/amd64,linux/arm64
  node14-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.NODE14 }}
        tags: 14.21-dev,14-dev
        dev: 1
        platform: linux/amd64,linux/arm64
